## Grid SearchCV

In [73]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [74]:
from sklearn.datasets import make_classification
X,Y=make_classification(n_samples=1000,random_state=42,n_classes=2,n_features=10,n_redundant=2,n_informative=8)

In [75]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=42,test_size=.28)

In [76]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()

In [77]:
params={
	"C":[1,1.1,0.1,0.01],
	"solver":['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'],
	"penalty": ['l1', 'l2', 'elasticnet']
}

In [78]:
from sklearn.model_selection import GridSearchCV
gridSerach=GridSearchCV(estimator=logistic,param_grid=params,cv=5,scoring='accuracy')

In [79]:
gridSerach.fit(X_train,Y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 1.1, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [80]:
gridSerach.best_params_

{'C': 0.01, 'penalty': 'l2', 'solver': 'liblinear'}

In [81]:
gridSerach.best_score_

0.7152777777777779

In [82]:
Y_pred=gridSerach.predict(X_test)

In [83]:
from sklearn.metrics import accuracy_score,precision_score,classification_report,confusion_matrix
print("Accuracy--> ",accuracy_score(Y_pred,Y_test)) 
print("Precision--> ",precision_score(Y_pred,Y_test))
print(classification_report(Y_pred,Y_test))     
print(confusion_matrix(Y_pred,Y_test))   

Accuracy-->  0.725
Precision-->  0.7913669064748201
              precision    recall  f1-score   support

           0       0.66      0.76      0.71       122
           1       0.79      0.70      0.74       158

    accuracy                           0.72       280
   macro avg       0.73      0.73      0.72       280
weighted avg       0.73      0.72      0.73       280

[[ 93  29]
 [ 48 110]]


# Randomized SearchCV

In [84]:
from sklearn.model_selection import RandomizedSearchCV
randomCV=RandomizedSearchCV(estimator=logistic,param_distributions=params,cv=5,scoring='accuracy')

In [85]:
randomCV.fit(X_train,Y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 1.1, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [86]:
randomCV.best_params_

{'solver': 'sag', 'penalty': 'l2', 'C': 1}

In [87]:
randomCV.best_score_

0.7125

In [88]:
Y_pred=randomCV.predict(X_test)
Y_pred

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0])

In [89]:
from sklearn.metrics import accuracy_score,precision_score,classification_report,confusion_matrix
print("Accuracy--> ",accuracy_score(Y_pred,Y_test)) 
print("Precision--> ",precision_score(Y_pred,Y_test))
print(classification_report(Y_pred,Y_test))     
print(confusion_matrix(Y_pred,Y_test))  

Accuracy-->  0.7071428571428572
Precision-->  0.7410071942446043
              precision    recall  f1-score   support

           0       0.67      0.73      0.70       131
           1       0.74      0.69      0.72       149

    accuracy                           0.71       280
   macro avg       0.71      0.71      0.71       280
weighted avg       0.71      0.71      0.71       280

[[ 95  36]
 [ 46 103]]
